# Generated by Django 3.0.7 on 2021-04-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
