# Generated by Django 3.0.7 on 2021-04-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_card_packageorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuspack',
            name='no_of_cars',
            field=models.IntegerField(default=0),
        ),
    ]
