# Generated by Django 3.0.7 on 2021-04-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210404_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='validity',
        ),
    ]
