# Generated by Django 3.0.7 on 2021-04-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210402_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Categori',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
