# Generated by Django 3.0.7 on 2021-04-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210402_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categori',
            name='description',
        ),
    ]
