# Generated by Django 3.0.7 on 2021-04-04 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20210402_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
